#!/bin/sh
#
# ifup hook script for advroute
#
# Licensed under the GNU GPL.  See /usr/share/common-licenses/GPL.
#

case "$ADDRFAM" in
  inet) : ;;
  *) exit 0 ;;
esac

if [ -z "$IF_RTTABLES" ] ; then
    # leave as default
    exit 0
fi

case "$METHOD" in
  static | manual | dhcp)
    for RT in $IF_RTTABLES; do
        # try get just the correct link route for the interface
        # on the main table
        /sbin/ip route list scope link table main proto kernel dev ${IFACE} \
        | while read ROUTE ; do
            # and add that route to all the tables mentioned in the rrtables option
            # in the interfaces file
            /sbin/ip route add table ${RT} scope link proto kernel dev ${IFACE} ${ROUTE}
        done
    done
    ;;
  *) exit 0 ;;
esac
